
target 'Segment-Taplytics_Example' do
  pod 'Segment-Taplytics', :path => '../'

  target 'Segment-Taplytics_Tests' do
    inherit! :search_paths

    pod 'OCMockito'
    pod 'Specta'
    pod 'Expecta'
  end
end
