
target 'Segment-Taplytics_Example', :exclusive => true do
  pod 'Segment-Taplytics', :path => '../'
end

target 'Segment-Taplytics_Tests', :exclusive => true do
  pod 'Segment-Taplytics', :path => '../'

  pod 'OCMockito'
  pod 'Specta'
  pod 'Expecta'
end
